config/routes.rb
Rails.application.routes.draw do
  root to: "travel_times#new"
  resources :travel_times, only: [:new, :create]
end

app/models/journey_segment.rb
class JourneySegment

  attr_reader :destination, :end_coords, :start_coords, :departure_time

  def initialize(params)
    @start_coords = params[:start_coords]
    @end_coords = params[:end_coords]
    @destination = params[:destination]
    @departure_time = format_depature_time(params[:departure_time])
  end

  def travel_time
    @travel_time ||= CitymapperApi.get_travel_time(start_coords, end_coords, departure_time)
  end

  def arrival_time
    @arrival_time ||= (Time.parse(departure_time) + (travel_time * 60)).strftime("%Y-%m-%dT%H:%M")
  end

  private
  
  def format_depature_time(departure_time)
    Time.parse(departure_time).strftime("%l:%M %p %m-%d-%Y")
  end

end

app/models/travel_time.rb
class TravelTime
  DEFAULT_START_COORDS = '51.520032,-0.0989399' # Rentify, London

  attr_reader :destinations
  attr_accessor :start_coords, :departure_time

  def self.parse(travel_time_params)
    new(travel_time_params).parse
  end

  def initialize(travel_time_params)
    @start_coords = DEFAULT_START_COORDS
    @departure_time = travel_time_params["departure_time"]
    @destinations = travel_time_params["destinations"].values
  end

  def parse
    travel_times = []
    start_coords = @start_coords
    departure_time = @departure_time 

    destinations.each do |destination|
      end_coords = destination["coords"]

      journey_segment_params = {
        start_coords: start_coords,
        end_coords: end_coords,
        destination: destination["address"],
        departure_time: departure_time, #time depart from previous destination
      }

      journey_segment = JourneySegment.new(journey_segment_params)
      travel_times << journey_segment
      return nil unless journey_segment.travel_time

      start_coords = journey_segment.end_coords
      departure_time = journey_segment.arrival_time
    end

    travel_times
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/travel_times_controller.rb
class TravelTimesController < ApplicationController

  def new
  end

  def create
    @travel_times = TravelTime.parse(travel_time_params)
    render :show
  end

  private

  def travel_time_params
    params.require(:travel_times)
      .permit(:departure_time, destinations: [:address, :coords])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travel_times_helper.rb
module TravelTimesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelTimeChallenge</title>
  <script src=<%= "https://maps.googleapis.com/maps/api/js?key=" + ENV["google_api_key"] + "&libraries=places" %>></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1 class="header">Travel Time Calculator</h1>

  <%= yield %>

</body>
</html>

app/views/travel_times/_itinerary.html.erb
<% if @travel_times.nil? %>
  <h2 class="header sub-header">An error occured, please try again.</h2>
<% else %>
  <h2 class="header sub-header">Itinerary</h2>
  <table class="itinerary">
    <tr>
      <th>Destination</th>
      <th>Address</th>
      <th>Travel Time</th>
      <th>Arrival Time</th>
    </tr>

    <% @travel_times.each_with_index do |travel_time, i|  %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= travel_time.address %></td>
        <td><%= travel_time.travel_time %> minutes</td>
        <td><%= travel_time.arrival_time %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/travel_times/new.html.erb
<form class="travel-times-form" action="<%= travel_times_url %>" method="post" id="form">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >

  <span>Starting Location: Rentify, Barbican, London</span>

  <label for="datetime">Date/Time of Departure:</label>
  <input
    id="datetime"
    type="datetime-local"
    name="travel_times[departure_time]"
    value="<%= Time.now.strftime("%Y-%m-%dT%H:%M") %>"
  >

  <div class="buttons">
    <button id="add-destination" class="button">Add Destination</button>
    <input id="submit" class="button" type="submit" value="Get travel times">
  </div>
</form>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const addDestination = document.getElementById('add-destination');
    addDestination.addEventListener('click', appendNewAutocomplete);
  });
</script>

app/views/travel_times/show.html.erb
<%= render partial: "itinerary", travel_times: @travel_times %>